[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nfl"
version = "0.1.0"
dependencies = [
    "torch",
    "pandas",
    "numpy",
    "pandera",
    "pyyaml",
]

[project.optional-dependencies]
dev = [
    "pip-tools",
    "pytest",
    "ipykernel",
    "ruff",
]