from enum import StrEnum

class NFLTeam(StrEnum):
    PHI = "PHI"
    IND = "IND"
    NO = "NO"
    TEN = "TEN"
    WAS = "WAS"
    SEA = "SEA"
    CHI = "CHI"
    DEN = "DEN"
    ATL = "ATL"
    NYJ = "NYJ"
    TB = "TB"
    GB = "GB"
    CLE = "CLE"
    JAX = "JAX"
    MIA = "MIA"
    DAL = "DAL"
    KC = "KC"
    DET = "DET"
    NE = "NE"
    CAR = "CAR"
    SF  = "SF"
    BUF = "BUF"
    MIN = "MIN"
    BAL = "BAL"
    CIN = "CIN"
    NYG = "NYG"
    LA = "LA"
    LV = "LV"
    LAC = "LAC"
    PIT = "PIT"
    ARI = "ARI"
    HOU = "HOU"

class PlayType(StrEnum):
    PASS = "pass"
    RUN = "run"
    KICK = "kickoff"
    PUNT = "punt"
    FIELD_GOAL = "field_goal"
    EXTRA_POINT = "extra_point"
    NO_PLAY = "no_play"
    QB_KNEEL = "qb_kneel"
    QB_SPIKE = "qb_spike"

class PassType(StrEnum):
    SHORT = "short"
    DEEP = "deep"

class TeamType(StrEnum):
    HOME = "home"
    AWAY = "away"

class SeasonType(StrEnum):
    REGULAR = "REG"
    POSTSEASON = "POST"

class PenaltyType(StrEnum):
    FALSE_START = "False Start"
    UNNECESSARY_ROUGHNESS = "Unnecessary Roughness"
    ROUGHING_THE_PASSER = "Roughing the Passer"
    OFFENSIVE_HOLDING = "Offensive Holding"
    DEFENSIVE_OFFSIDE = "Defensive Offside"
    ILLEGAL_FORMATION = "Illegal Formation"
    ILLEGAL_CONTACT = "Illegal Contact"
    ENCROACHMENT = "Encroachment"
    DELAY_OF_GAME = "Delay of Game"
    FAIR_CATCH_INTERFERENCE = "Fair Catch Interference"
    DEFENSIVE_HOLDING = "Defensive Holding"
    ILLEGAL_MOTION = "Illegal Motion"
    UNSPORTSMANLIKE_CONDUCT = "Unsportsmanlike Conduct"
    OFFENSIVE_PASS_INTERFERENCE = "Offensive Pass Interference"
    ILLEGAL_BLOCK_ABOVE_THE_WAIST = "Illegal Block Above the Waist"
    DEFENSIVE_PASS_INTERFERENCE = "Defensive Pass Interference"
    FACE_MASK = "Face Mask"
    TRIPPING = "Tripping"
    ILLEGAL_SHIFT = "Illegal Shift"
    INELIGIBLE_DOWNFIELD_PASS = "Ineligible Downfield Pass"
    ILLEGAL_SUBSTITUTION = "Illegal Substitution"
    FACE_MASK_5_YARDS = "Face Mask (5 Yards)"
    INTENTIONAL_GROUNDING = "Intentional Grounding"
    DEFENSIVE_12_ON_FIELD = "Defensive 12 On-field"
    ILLEGAL_USE_OF_HANDS = "Illegal Use of Hands"
    INELIGIBLE_DOWNFIELD_KICK = "Ineligible Downfield Kick"
    KICKOFF_OUT_OF_BOUNDS = "Kickoff Out of Bounds"
    CLIPPING = "Clipping"
    ILLEGAL_FORWARD_PASS = "Illegal Forward Pass"
    OFFENSIVE_12_ON_FIELD = "Offensive 12 On-field"
    ILLEGAL_TOUCH_KICK = "Illegal Touch Kick"
    NEUTRAL_ZONE_INFRACTION = "Neutral Zone Infraction"
    TAUNTING = "Taunting"
    RUNNING_INTO_THE_KICKER = "Running Into the Kicker"
    DISQUALIFICATION = "Disqualification"
    OFFENSIVE_OFFSIDE = "Offensive Offside"
    ROUGHING_THE_KICKER = "Roughing the Kicker"
    OFFSIDE_ON_FREE_KICK = "Offside on Free Kick"
    DEFENSIVE_DELAY_OF_GAME = "Defensive Delay of Game"
    CHOP_BLOCK = "Chop Block"
    PERSONAL_FOUL = "Personal Foul"
    ILLEGAL_CUT = "Illegal Cut"
    ILLEGAL_CRACKBACK = "Illegal Crackback"
    ILLEGAL_TOUCH_PASS = "Illegal Touch Pass"
    ILLEGAL_BLINDSIDE_BLOCK = "Illegal Blindside Block"
    SHORT_FREE_KICK = "Short Free Kick"
    LEVERAGE = "Leverage"
    ILLEGALLY_KICKING_BALL = "Illegally Kicking Ball"
    DELAY_OF_KICKOFF = "Delay of Kickoff"
    INVALID_FAIR_CATCH_SIGNAL = "Invalid Fair Catch Signal"
    LEAPING = "Leaping"
    LOW_BLOCK = "Low Block"
    INTERFERENCE_WITH_OPPORTUNITY_TO_CATCH = "Interference with Opportunity to Catch"
    LOWERING_THE_HEAD_TO_MAKE_FORCIBLE_CONTACT = "Lowering the Head to Make Forcible Contact"
    DEFENSIVE_TOO_MANY_MEN_ON_FIELD = "Defensive Too Many Men on Field"
    PLAYER_OUT_OF_BOUNDS_ON_KICK = "Player Out of Bounds on Kick"
    HORSE_COLLAR_TACKLE = "Horse Collar Tackle"
    ILLEGAL_PEELBACK = "Illegal Peelback"
    OFFENSIVE_TOO_MANY_MEN_ON_FIELD = "Offensive Too Many Men on Field"
    KICK_CATCH_INTERFERENCE = "Kick Catch Interference"
    ILLEGAL_DOUBLE_TEAM_BLOCK = "Illegal Double-Team Block"
    ILLEGAL_KICK_KICKING_LOOSE_BALL = "Illegal Kick/Kicking Loose Ball"
    ILLEGAL_BAT = "Illegal Bat"
    LOWERING_THE_HEAD_TO_INITIATE_CONTACT = "Lowering the Head to Initiate Contact"
    ILLEGAL_WEDGE = "Illegal Wedge"
    KICKOFF_SHORT_OF_LANDING_ZONE = "Kickoff Short of Landing Zone"
    HIP_DROP_TACKLE = "Hip Drop Tackle"
    ILLEGAL_SCRIMMAGE_KICK = "Illegal Scrimmage Kick"
    ILLEGAL_KICK = "Illegal Kick"

class SurfaceType(StrEnum):
    GRASS = "grass"
    FIELDTURF = "fieldturf"
    SPORTTURF = "sportturf"
    MATRIXTURF = "matrixurf"
    A_TURF = "a_turf"
    FIELDTURF_MISSPELLING = "fieldturf "
    ASTROPLAY = "astroplay"

class NFLPlayType(StrEnum):
    GAME_START = "GAME_START"
    KICK_OFF = "KICK_OFF"
    RUSH = "RUSH"
    PASS = "PASS"
    PUNT = "PUNT"
    PENALTY = "PENALTY"
    XP_KICK = "XP_KICK"
    TIMEOUT = "TIMEOUT"
    FIELD_GOAL = "FIELD_GOAL"
    SACK = "SACK"
    END_QUARTER = "END_QUARTER"
    INTERCEPTION = "INTERCEPTION"
    UNSPECIFIED = "UNSPECIFIED"
    END_GAME = "END_GAME"
    FUMBLE_RECOVERED_BY_OPPONENT = "FUMBLE_RECOVERED_BY_OPPONENT"
    PAT2 = "PAT2"
    COMMENT = "COMMENT"
    FREE_KICK = "FREE_KICK"

class RunLocations(StrEnum):
    LEFT = "left"
    RIGHT = "right"
    MIDDLE ="middle"

class FieldGoalResults(StrEnum):
    MADE = "made"
    BLOCKED = "blocked"
    MISSED = "missed"

class RunGaps(StrEnum):
    END = "end"
    GUARD = "guard"
    TACKLE = "tackle"

class Result(StrEnum):
    FAILURE = "failure"
    SUCCESS = "success"

class Half(StrEnum):
    FIRST = "Half1"
    SECOND = "Half2"
    OVERTIME = "Overtime"

class DriveResult(StrEnum):
    PUNT = "Punt"
    TOUCHDOWN = "Touchdown"
    TURNOVER = "Turnover"
    FIELD_GOAL = "Field goal"
    MISSED_FIELD_GOAL = "Missed field goal"
    OPP_TOUCHDOWN = "Opp touchdown"
    END_OF_HALF = "End of half"
    SAFTEY = "Saftey"
    TURNOVER_ON_DOWNS = "Turnover on downs"

class SpecialTeamsPlayType(StrEnum):
    PENALTY = 'Penalty'

class DriveStartReason(StrEnum):
    PUNT = "Punt"
    TOUCHDOWN = "Touchdown"
    INTERCEPTION = "Interception"
    FUMBLE = "Fumble"
    FIELD_GOAL = "Field Goal"
    BLOCKED_FG = "Blocked FG"
    END_OF_HALF = "End of Half"
    MISSED_FG = "Missed FG"
    SAFETY = "Safety"
    DOWNS = "Downs"
    FUMBLE_SAFETY = "Fumble, Safety"
    BLOCKED_PUNT = "Blocked Punt"
    BLOCKED_PUNT_DOWNS = "Blocked Punt, Downs"
    BLOCKED_FG_DOWNS = "Blocked FG, Downs"
    UNKNOWN = "UNKNOWN"
    KICKOFF = "KICKOFF"
    PUNT_UPPER = "PUNT"
    INTERCEPTION_UPPER = "INTERCEPTION"
    FUMBLE_UPPER = "FUMBLE"
    DOWNS_UPPER = "DOWNS"
    MISSED_FG_UPPER = "MISSED_FG"
    BLOCKED_FG_UPPER = "BLOCKED_FG"
    BLOCKED_FG_DOWNS_UPPER = "BLOCKED_FG,_DOWNS"
    MUFFED_PUNT = "MUFFED_PUNT"
    ONSIDE_KICK = "ONSIDE_KICK"
    BLOCKED_PUNT_UPPER = "BLOCKED_PUNT"
    BLOCKED_PUNT_DOWNS_UPPER = "BLOCKED_PUNT,_DOWNS"
    MUFFED_KICKOFF = "MUFFED_KICKOFF"
    BLOCKED_PUNT_DOWNS_ALT = "BLOCKED_PUNT_DOWNS"
    OWN_KICKOFF = "OWN_KICKOFF"
    MUFFED_FG = "MUFFED_FG"
    BLOCKED_FG_DOWNS_ALT = "BLOCKED_FG_DOWNS"
