bool_columns:
- lateral_recovery
- first_down_penalty
- third_down_converted
- aborted_play
- fumble_not_forced
- kickoff_downed
- success
- tackled_for_loss
- kickoff_attempt
- return_touchdown
- qb_kneel
- sp
- saftey
- lateral_rush
- qb_hit
- punt_downed
- fumble
- solo_tackle
- defensive_two_point_attempt
- pass_attempt
- rush_touchdown
- defensive_two_point_conv
- third_down_failed
- punt_attempt
- two_point_attempt
- no_huddle
- sack
- rush_attempt
- defensive_extra_point_conv
- qb_dropback
- pass
- own_kickoff_recovery
- series_success
- punt_fair_catch
- pass_touchdown
- goal_to_go
- timeout
- tackle_with_assist
- lateral_return
- special
- incomplete_pass
- drive_inside_20
- punt_inside_twenty
- kickoff_inside_twenty
- extra_point_attempt
- qb_scramble
- interception
- play
- first_down_pass
- kickoff_fair_catch
- assist_tackle
- own_kickoff_recovery_td
- lateral_reception
- quarter_end
- penalty
- div_game
- shotgun
- drive_ended_with_score
- saftey
- fumble_forced
- touchdown
- rush
- punt_out_of_bounds
- kickoff_in_endzone
- punt_in_endzone
- kickoff_out_of_bounds
- fumble_out_of_bounds
- fumble_lost
- home_opening_kickoff
- first_down
- qb_spike
- first_down_rush
- replay_or_challenge
- touchback
- fourth_down_failed
- complete_pass
- out_of_bounds
- fourth_down_converted
- field_goal_attempt

drop_columns:
- play_id
- week
- fixed_drive
- season_type
- passer
- posteam
- receiver
- vegas
- lateral
- away_wp
- total_home_score
- play_deleted
- away_coach
- defteam_score_post
- location
- jersey_number
- home_coach
- _tackle_player_
- stadium
- game_half
- posteam_timeouts_remaining
- defteam
- nfl_api_id
- half_seconds_remaining
- desc
- defensive_extra_point_
- _with_assist_team_fumble_recovery_
- time
- home_score
- game_date
- away_score
- player_id
- defteam_timeouts_remaining
- _epa
- punt
- name
- posteam_score_post
- quarter_seconds_remaining
- id
- kickoff
- two_point
- old_game_id
- player_name
- spread
- fantasy
- _team
- total_away_score
- total
- def_wp
- kick
- forced_fumble_player_
- rusher
- _prob
- weather
- home_team
- away_team
- posteam
- defteam
- side_of_field
- yrdln
- player_name
- player_id

yardline_columns:
- yrdln
- end_yard_line
- drive_start_yard_line
- drive_end_yard_line

date_columns:
- game_date
